-- Bump Beeper core schema: shared bump map + fleet pilot.
-- Rules: RLS on for every table, deny by default; clients write only through SECURITY DEFINER RPCs
-- with an empty search_path; raw observations are merged into spots and deleted after 30 days.

create extension if not exists postgis with schema extensions;

-- ---------------------------------------------------------------- tables

create table public.devices (
  id uuid primary key default auth.uid() references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  app_version text,
  os_api int,
  consent_version int,
  share_enabled boolean not null default false,
  trust real not null default 1.0
);

-- One row per hazard event a phone reports. No tracks: single points, time rounded to the hour.
create table public.observations (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices (id) on delete cascade,
  client_obs_id uuid not null,
  kind text not null check (kind in ('jolt', 'known_hit', 'pass_clear')),
  geom extensions.geography(Point, 4326) not null,
  heading smallint check (heading between 0 and 359),
  speed_kmh smallint check (speed_kmh between 0 and 250),
  peak real,
  kind_score real,
  side_score real,
  observed_hour timestamptz not null,
  processed boolean not null default false,
  created_at timestamptz not null default now(),
  unique (device_id, client_obs_id)
);
create index observations_unprocessed_idx on public.observations (id) where not processed;
create index observations_device_day_idx on public.observations (device_id, created_at);

create table public.spots (
  id bigint generated by default as identity primary key,
  geom extensions.geography(Point, 4326) not null,
  heading smallint check (heading between 0 and 359),
  kind text,
  side text,
  severity real,
  n_devices int not null default 0,
  n_hits int not null default 0,
  n_clear int not null default 0,
  status text not null default 'candidate' check (status in ('candidate', 'confirmed', 'stale', 'retired')),
  first_seen timestamptz not null default now(),
  last_hit timestamptz,
  updated_at timestamptz not null default now()
);
create index spots_geom_idx on public.spots using gist (geom);

create table public.spot_contributors (
  spot_id bigint not null references public.spots (id) on delete cascade,
  device_id uuid not null references public.devices (id) on delete cascade,
  hits int not null default 0,
  clears int not null default 0,
  last_at timestamptz,
  primary key (spot_id, device_id)
);
create index spot_contributors_device_idx on public.spot_contributors (device_id);

create table public.fleets (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table public.memberships (
  user_id uuid not null references auth.users (id) on delete cascade,
  fleet_id bigint not null references public.fleets (id) on delete cascade,
  role text not null check (role in ('owner', 'admin', 'viewer')),
  primary key (user_id, fleet_id)
);
create index memberships_fleet_idx on public.memberships (fleet_id);

create table public.vehicles (
  id bigint generated by default as identity primary key,
  fleet_id bigint not null references public.fleets (id) on delete cascade,
  label text not null
);
create index vehicles_fleet_idx on public.vehicles (fleet_id);

create table public.drivers (
  id bigint generated by default as identity primary key,
  fleet_id bigint not null references public.fleets (id) on delete cascade,
  display_name text not null,
  device_id uuid references public.devices (id) on delete set null,
  vehicle_id bigint references public.vehicles (id) on delete set null,
  on_shift boolean not null default false,
  active boolean not null default true
);
create index drivers_fleet_idx on public.drivers (fleet_id);
create index drivers_device_idx on public.drivers (device_id);
create index drivers_vehicle_idx on public.drivers (vehicle_id);

create table public.invites (
  code text primary key,
  fleet_id bigint not null references public.fleets (id) on delete cascade,
  driver_id bigint references public.drivers (id) on delete cascade,
  expires_at timestamptz not null default now() + interval '7 days',
  used_at timestamptz
);
create index invites_fleet_idx on public.invites (fleet_id);
create index invites_driver_idx on public.invites (driver_id);

create table public.trips (
  id bigint generated by default as identity primary key,
  device_id uuid not null references public.devices (id) on delete cascade,
  driver_id bigint references public.drivers (id) on delete set null,
  fleet_id bigint references public.fleets (id) on delete cascade,
  started_at timestamptz not null,
  ended_at timestamptz,
  distance_m int,
  score smallint check (score between 0 and 100),
  moving_s int,
  speeding_s int,
  harsh_brakes int,
  harsh_accels int,
  harsh_corners int,
  swerves int,
  bumps_fast int,
  phone_use int
);
create index trips_device_idx on public.trips (device_id);
create index trips_fleet_idx on public.trips (fleet_id);
create index trips_driver_idx on public.trips (driver_id);

create table public.trip_events (
  id bigint generated by default as identity primary key,
  trip_id bigint not null references public.trips (id) on delete cascade,
  kind text not null,
  geom extensions.geography(Point, 4326),
  speed_kmh smallint,
  value real,
  at timestamptz not null
);
create index trip_events_trip_idx on public.trip_events (trip_id);

create table public.crash_reports (
  id bigint generated by default as identity primary key,
  device_id uuid not null default auth.uid() references public.devices (id) on delete cascade,
  app_version text,
  at timestamptz not null default now(),
  stack text check (length(stack) <= 20000),
  model text
);
create index crash_reports_device_idx on public.crash_reports (device_id);

-- ---------------------------------------------------------------- grants (table level)
-- Supabase grants everything to anon/authenticated by default; RLS is the main wall, grants the second.

alter table public.devices enable row level security;
alter table public.observations enable row level security;
alter table public.spots enable row level security;
alter table public.spot_contributors enable row level security;
alter table public.fleets enable row level security;
alter table public.memberships enable row level security;
alter table public.vehicles enable row level security;
alter table public.drivers enable row level security;
alter table public.invites enable row level security;
alter table public.trips enable row level security;
alter table public.trip_events enable row level security;
alter table public.crash_reports enable row level security;

revoke all on all tables in schema public from anon;
-- TRUNCATE ignores RLS, so nobody outside the server gets it.
revoke truncate, references, trigger on all tables in schema public from authenticated;
revoke all on public.observations, public.spot_contributors from authenticated;
revoke insert, update, delete on public.spots, public.trips, public.trip_events from authenticated;
-- Devices are created by register_device; a phone may only change its own settings, never its trust.
revoke insert, update, delete on public.devices from authenticated;
grant update (app_version, os_api, consent_version, share_enabled) on public.devices to authenticated;
-- Linking a driver to a device happens through the (future) join RPC, not by an admin typing a uuid.
revoke insert, update on public.drivers from authenticated;
grant insert (fleet_id, display_name, vehicle_id, on_shift, active) on public.drivers to authenticated;
grant update (display_name, vehicle_id, on_shift, active) on public.drivers to authenticated;
revoke select, update, delete on public.crash_reports from authenticated;

-- ---------------------------------------------------------------- policies

create function public.is_fleet_member(fid bigint, roles text[])
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1 from public.memberships m
    where m.user_id = (select auth.uid())
      and m.fleet_id = fid
      and (roles is null or m.role = any (roles))
  );
$$;

create policy devices_select_own on public.devices for select to authenticated
  using (id = (select auth.uid()));
create policy devices_update_own on public.devices for update to authenticated
  using (id = (select auth.uid())) with check (id = (select auth.uid()));

-- observations, spot_contributors: no policies on purpose (only reachable through RPCs).

create policy spots_select_confirmed on public.spots for select to authenticated
  using (status = 'confirmed');

create policy fleets_select on public.fleets for select to authenticated
  using (public.is_fleet_member(id, null));
create policy fleets_update on public.fleets for update to authenticated
  using (public.is_fleet_member(id, array['owner', 'admin']))
  with check (public.is_fleet_member(id, array['owner', 'admin']));
create policy fleets_delete on public.fleets for delete to authenticated
  using (public.is_fleet_member(id, array['owner']));

create policy memberships_select on public.memberships for select to authenticated
  using (public.is_fleet_member(fleet_id, null));
create policy memberships_write on public.memberships for all to authenticated
  using (public.is_fleet_member(fleet_id, array['owner', 'admin']))
  with check (public.is_fleet_member(fleet_id, array['owner', 'admin']));

create policy vehicles_select on public.vehicles for select to authenticated
  using (public.is_fleet_member(fleet_id, null));
create policy vehicles_write on public.vehicles for all to authenticated
  using (public.is_fleet_member(fleet_id, array['owner', 'admin']))
  with check (public.is_fleet_member(fleet_id, array['owner', 'admin']));

create policy drivers_select on public.drivers for select to authenticated
  using (public.is_fleet_member(fleet_id, null));
create policy drivers_write on public.drivers for all to authenticated
  using (public.is_fleet_member(fleet_id, array['owner', 'admin']))
  with check (public.is_fleet_member(fleet_id, array['owner', 'admin']));

-- Invite codes are secrets: viewers don't see them.
create policy invites_admin on public.invites for all to authenticated
  using (public.is_fleet_member(fleet_id, array['owner', 'admin']))
  with check (public.is_fleet_member(fleet_id, array['owner', 'admin']));

create policy trips_select on public.trips for select to authenticated
  using (device_id = (select auth.uid()) or public.is_fleet_member(fleet_id, null));
-- trip_events follow their trip (the subquery is itself filtered by trips_select).
create policy trip_events_select on public.trip_events for select to authenticated
  using (exists (select 1 from public.trips t where t.id = trip_id));

create policy crash_reports_insert_own on public.crash_reports for insert to authenticated
  with check (device_id = (select auth.uid()));

-- ---------------------------------------------------------------- RPCs

-- Creates or refreshes the caller's device row. Returns the device id (= the auth user id).
create function public.register_device(app_version text, os_api int, consent_version int, share_enabled boolean)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
begin
  if uid is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  insert into public.devices as d (id, app_version, os_api, consent_version, share_enabled)
  values (uid, register_device.app_version, register_device.os_api,
          register_device.consent_version, coalesce(register_device.share_enabled, false))
  on conflict (id) do update
    set app_version = excluded.app_version,
        os_api = excluded.os_api,
        consent_version = excluded.consent_version,
        share_enabled = excluded.share_enabled;
  return uid;
end;
$$;

-- Accepts up to 500 hazard observations. Element format:
--   {"client_obs_id": uuid, "kind": "jolt|known_hit|pass_clear", "lat": n, "lon": n,
--    "heading": 0-359, "speed_kmh": n, "peak": n, "kind_score": n, "side_score": n, "observed_at": iso8601}
-- The whole batch is rejected (22023) if any element is invalid. Returns the client ids the server
-- now holds (new or already known), so the phone can clear them from its outbox.
create function public.submit_observations(batch jsonb)
returns uuid[]
language plpgsql
security definer
set search_path = ''
as $$
declare
  uid uuid := auth.uid();
  n int;
  bad int;
  recent int;
begin
  if uid is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  if not exists (select 1 from public.devices d where d.id = uid and d.share_enabled) then
    raise exception 'device not registered or sharing is off' using errcode = '42501';
  end if;
  if batch is null or jsonb_typeof(batch) <> 'array' then
    raise exception 'batch must be a JSON array' using errcode = '22023';
  end if;
  n := jsonb_array_length(batch);
  if n = 0 then
    return '{}'::uuid[];
  end if;
  if n > 500 then
    raise exception 'batch too large (% > 500)', n using errcode = '22023';
  end if;

  -- Egypt / MENA box only; times within the last 30 days.
  select count(*) into bad
  from jsonb_array_elements(batch) e
  where not coalesce(
    jsonb_typeof(e) = 'object'
    and e ->> 'client_obs_id' is not null
    and e ->> 'kind' in ('jolt', 'known_hit', 'pass_clear')
    and jsonb_typeof(e -> 'lat') = 'number'
    and jsonb_typeof(e -> 'lon') = 'number'
    and (e ->> 'lat')::double precision between 12 and 38
    and (e ->> 'lon')::double precision between 24 and 60
    and (e ->> 'observed_at')::timestamptz between now() - interval '30 days' and now() + interval '1 hour',
    false);
  if bad > 0 then
    raise exception '% invalid observation(s) in batch', bad using errcode = '22023';
  end if;

  select count(*) into recent
  from public.observations o
  where o.device_id = uid and o.created_at > now() - interval '1 day';
  if recent + n > 2000 then
    raise exception 'daily upload limit reached' using errcode = '54000';
  end if;

  insert into public.observations
    (device_id, client_obs_id, kind, geom, heading, speed_kmh, peak, kind_score, side_score, observed_hour)
  select uid,
         (e ->> 'client_obs_id')::uuid,
         e ->> 'kind',
         extensions.st_setsrid(
           extensions.st_makepoint((e ->> 'lon')::double precision, (e ->> 'lat')::double precision), 4326
         )::extensions.geography,
         (e ->> 'heading')::smallint,
         (e ->> 'speed_kmh')::smallint,
         (e ->> 'peak')::real,
         (e ->> 'kind_score')::real,
         (e ->> 'side_score')::real,
         date_trunc('hour', (e ->> 'observed_at')::timestamptz)
  from jsonb_array_elements(batch) e
  on conflict (device_id, client_obs_id) do nothing;

  return (select array_agg(distinct (e ->> 'client_obs_id')::uuid) from jsonb_array_elements(batch) e);
end;
$$;

-- Confirmed spots around a point; radius capped at 10 km.
create function public.spots_near(lat double precision, lon double precision, radius_m int default 3000)
returns table (
  id bigint,
  latitude double precision,
  longitude double precision,
  heading smallint,
  kind text,
  side text,
  severity real,
  n_devices int,
  last_hit timestamptz
)
language sql
stable
security definer
set search_path = ''
as $$
  select s.id,
         extensions.st_y(s.geom::extensions.geometry),
         extensions.st_x(s.geom::extensions.geometry),
         s.heading, s.kind, s.side, s.severity, s.n_devices, s.last_hit
  from public.spots s
  where s.status = 'confirmed'
    and extensions.st_dwithin(
          s.geom,
          extensions.st_setsrid(extensions.st_makepoint(spots_near.lon, spots_near.lat), 4326)::extensions.geography,
          least(greatest(coalesce(spots_near.radius_m, 3000), 0), 10000)::double precision)
  order by s.id
  limit 5000;
$$;

-- Deletes the caller's device and, by cascade, its observations, contributions, trips and crash reports.
-- Merged spots stay: they no longer point to any device.
create function public.forget_me()
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  delete from public.devices d where d.id = auth.uid();
end;
$$;

-- ---------------------------------------------------------------- aggregation (server only)

-- Merges unprocessed observations into spots (15 m, heading within 45 degrees), updates counters and
-- status, and deletes processed observations older than 30 days. Returns how many it processed.
create function public.aggregate_observations()
returns int
language plpgsql
security definer
set search_path = ''
as $$
declare
  o record;
  sid bigint;
  is_hit boolean;
  touched bigint[] := '{}';
  done int := 0;
begin
  for o in
    select ob.id, ob.device_id, ob.kind, ob.geom, ob.heading, ob.peak, ob.kind_score, ob.side_score, ob.observed_hour
    from public.observations ob
    where not ob.processed
    order by ob.id
    for update skip locked
  loop
    is_hit := o.kind <> 'pass_clear';
    select s.id into sid
    from public.spots s
    where s.status <> 'retired'
      and extensions.st_dwithin(s.geom, o.geom, 15)
      and (s.heading is null or o.heading is null
           or abs(((s.heading::int - o.heading::int) % 360 + 540) % 360 - 180) <= 45)
    order by extensions.st_distance(s.geom, o.geom)
    limit 1;

    if sid is null and is_hit then
      insert into public.spots (geom, heading, kind, side, severity, first_seen, last_hit)
      values (o.geom, o.heading,
              case when o.kind_score is null then null when o.kind_score >= 0.5 then 'pothole' else 'bump' end,
              case when o.side_score is null then null when o.side_score > 0.33 then 'right'
                   when o.side_score < -0.33 then 'left' else 'both' end,
              o.peak, o.observed_hour, o.observed_hour)
      returning id into sid;
    end if;

    if sid is not null then
      insert into public.spot_contributors as c (spot_id, device_id, hits, clears, last_at)
      values (sid, o.device_id, case when is_hit then 1 else 0 end, case when is_hit then 0 else 1 end, o.observed_hour)
      on conflict (spot_id, device_id) do update
        set hits = c.hits + excluded.hits,
            clears = c.clears + excluded.clears,
            last_at = greatest(c.last_at, excluded.last_at);
      if is_hit then
        update public.spots s
        set last_hit = greatest(s.last_hit, o.observed_hour),
            severity = case when o.peak is null then s.severity
                            else coalesce(0.8 * s.severity + 0.2 * o.peak, o.peak) end
        where s.id = sid;
      end if;
      touched := touched || sid;
    end if;

    update public.observations set processed = true where id = o.id;
    done := done + 1;
  end loop;

  update public.spots s
  set n_devices = c.n_dev, n_hits = c.n_hits, n_clear = c.n_clear, updated_at = now()
  from (
    select sc.spot_id,
           count(*) filter (where sc.hits > 0)::int as n_dev,
           sum(sc.hits)::int as n_hits,
           sum(sc.clears)::int as n_clear
    from public.spot_contributors sc
    where sc.spot_id = any (touched)
    group by sc.spot_id
  ) c
  where s.id = c.spot_id;

  -- Confirm with 3 devices (2 if one is a fleet driver's phone) and at least half of the passes hit.
  update public.spots s
  set status = case
      when s.n_hits::real / greatest(s.n_hits + s.n_clear, 1) >= 0.5
           and s.n_devices >= case when exists (
                 select 1 from public.spot_contributors sc
                 join public.drivers d on d.device_id = sc.device_id and d.active
                 where sc.spot_id = s.id and sc.hits > 0) then 2 else 3 end
        then 'confirmed'
      when s.status = 'confirmed' then 'stale'
      else s.status end
  where s.id = any (touched) and s.status <> 'retired';

  delete from public.observations ob where ob.processed and ob.created_at < now() - interval '30 days';
  return done;
end;
$$;

-- Supabase grants EXECUTE on new functions to everyone; take it back and hand out only what clients need.
revoke execute on function public.is_fleet_member(bigint, text[]) from public, anon;
revoke execute on function public.register_device(text, int, int, boolean) from public, anon;
revoke execute on function public.submit_observations(jsonb) from public, anon;
revoke execute on function public.spots_near(double precision, double precision, int) from public, anon;
revoke execute on function public.forget_me() from public, anon;
revoke execute on function public.aggregate_observations() from public, anon, authenticated;
grant execute on function public.is_fleet_member(bigint, text[]) to authenticated;
grant execute on function public.register_device(text, int, int, boolean) to authenticated;
grant execute on function public.submit_observations(jsonb) to authenticated;
grant execute on function public.spots_near(double precision, double precision, int) to authenticated;
grant execute on function public.forget_me() to authenticated;

-- Run the aggregation every 10 minutes where pg_cron exists (hosted project: enable it first, see README).
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron with schema pg_catalog;
    perform cron.schedule('aggregate-observations', '*/10 * * * *', 'select public.aggregate_observations()');
  end if;
exception when others then
  raise notice 'pg_cron not scheduled: %', sqlerrm;
end;
$$;
