-- "Help improve detection": consented, compact learning samples (no raw recordings, no routes).
-- One row per jolt candidate the engine judged (or the user muted): a short window of vertical accel (+ gyro roll/pitch)
-- as little-endian int16, the decision and its features. Plus one summary row per trip, without a route.
-- Separate opt-in from the shared map. Rows carry a random pseudonym (new on every opt-in), never the account id.
-- Free plan: per-device and project daily caps and a size guard (README).

-- ---------------------------------------------------------------- consent (server-side, with a timestamp)
alter table public.devices
  add column training_consent boolean not null default false,
  add column training_consent_at timestamptz,
  add column training_consent_version int check (training_consent_version between 0 and 1000),
  -- Random pseudonym for the training rows; null while not opted in, so a later opt-in can't be linked to an earlier one.
  add column training_subject uuid unique;
-- No column grant: only set_training_consent() changes these (the devices column grants stay as they are).

-- ---------------------------------------------------------------- tables
create table public.training_samples (
  id bigint generated by default as identity primary key,
  subject uuid not null references public.devices (training_subject) on delete cascade,
  client_sample_id uuid not null,
  received_on date not null default current_date,          -- server day: caps and 12-month retention
  day date not null,                                       -- drive day only, never a time of day
  decision text not null check (decision in ('learned', 'hit', 'rejected', 'miss', 'pass_clear', 'user_mute')),
  reason text check (reason ~ '^[a-z_]{1,24}$'),
  label_source text not null check (label_source in ('engine', 'user_mute', 'manual')),
  label text check (label in ('bump', 'pothole', 'none', 'unsure')),  -- set later by hand (label_source = manual)
  classification text check (classification in ('bump', 'pothole', 'unsure')),
  placement text not null check (placement in ('mounted', 'cupholder', 'pocket', 'unknown')),
  speed_kmh real not null check (speed_kmh between 0 and 250),
  heading_change_deg real check (heading_change_deg between -180 and 180),
  gps_accuracy_m real check (gps_accuracy_m between 0 and 500),
  peak real check (peak between 0 and 100),
  shape_score real check (shape_score between -1 and 1),
  first_down boolean,
  roll_pitch_ratio real check (roll_pitch_ratio between 0 and 1000),
  side_score real check (side_score between -1 and 1),
  spot_id bigint references public.spots (id) on delete set null,  -- confirmed shared spots only; no other location
  sdk smallint not null check (sdk between 29 and 100),
  app_version text not null check (length(app_version) between 1 and 40),
  brand text check (brand ~ '^[a-z0-9 _-]{1,20}$'),
  rate_hz smallint not null check (rate_hz between 20 and 200),
  pre_ms smallint not null check (pre_ms between 0 and 2000),
  -- int16 little-endian: accel 0.004 m/s² per unit, gyro 0.001 rad/s per unit (README). 2..4 s at rate_hz.
  accel_v bytea not null,
  gyro_roll bytea,
  gyro_pitch bytea,
  check (octet_length(accel_v) between 4 * rate_hz and 2 * (4 * rate_hz + 1) and octet_length(accel_v) % 2 = 0),
  check ((gyro_roll is null) = (gyro_pitch is null)),
  check (gyro_roll is null or (octet_length(gyro_roll) = octet_length(accel_v)
                               and octet_length(gyro_pitch) = octet_length(accel_v))),
  check (pre_ms::int * rate_hz <= 1000 * (octet_length(accel_v) / 2 - 1)),  -- the trigger lies inside the window
  check (day between received_on - 31 and received_on + 1),
  unique (subject, client_sample_id)
);
-- Rows arrive in day order, so a BRIN index makes the retention delete cheap at almost no size.
create index training_samples_received_brin on public.training_samples using brin (received_on);
create index training_samples_spot_idx on public.training_samples (spot_id) where spot_id is not null;
create table public.training_trips (
  id bigint generated by default as identity primary key,
  subject uuid not null references public.devices (training_subject) on delete cascade,
  client_trip_id uuid not null,
  received_on date not null default current_date,
  day date not null check (day between received_on - 31 and received_on + 1),
  placement text not null check (placement in ('mounted', 'cupholder', 'pocket', 'unknown')),
  sdk smallint not null check (sdk between 29 and 100),
  app_version text not null check (length(app_version) between 1 and 40),
  brand text check (brand ~ '^[a-z0-9 _-]{1,20}$'),
  duration_s int not null check (duration_s between 0 and 86400),
  distance_m int not null check (distance_m between 0 and 2000000),
  n_learned int check (n_learned between 0 and 10000), n_hit int check (n_hit between 0 and 10000),
  n_rejected int check (n_rejected between 0 and 10000), n_miss int check (n_miss between 0 and 10000),
  n_pass_clear int check (n_pass_clear between 0 and 10000), n_user_mute int check (n_user_mute between 0 and 10000),
  n_beeps int check (n_beeps between 0 and 10000), battery_start smallint check (battery_start between 0 and 100),
  battery_end smallint check (battery_end between 0 and 100), score smallint check (score between 0 and 100),
  speeding_s int check (speeding_s between 0 and 86400), harsh_brakes int check (harsh_brakes between 0 and 10000),
  harsh_accels int check (harsh_accels between 0 and 10000),
  harsh_corners int check (harsh_corners between 0 and 10000), swerves int check (swerves between 0 and 10000),
  bumps_fast int check (bumps_fast between 0 and 10000), phone_use int check (phone_use between 0 and 10000),
  unique (subject, client_trip_id)
);
create index training_trips_received_brin on public.training_trips using brin (received_on);
-- Per device and server day: counts only. Kept when consent is withdrawn (so toggling cannot reset the caps),
-- pruned after 2 days, deleted with the device.
create table public.training_quota (
  device_id uuid not null references public.devices (id) on delete cascade,
  day date not null,
  samples int not null default 0,
  bytes int not null default 0,
  trips int not null default 0,
  primary key (device_id, day)
);
-- Samples per UTC day for the whole project (throwaway anonymous accounts can't fill the guard in a day).
create table public.training_quota_total (
  day date primary key,
  samples int not null default 0
);
alter table public.training_samples enable row level security;
alter table public.training_trips enable row level security;
alter table public.training_quota enable row level security;
alter table public.training_quota_total enable row level security;
-- No policies at all: no client reads or writes. Grants are the second wall.
revoke all on public.training_samples, public.training_trips, public.training_quota, public.training_quota_total
  from public, anon, authenticated;
-- Size guard knob (MB of all training tables together); the owner can lower it with one UPDATE.
insert into public.app_settings (key, value) values ('training_max_mb', '200') on conflict (key) do nothing;

-- ---------------------------------------------------------------- RPCs
-- Turns "Help improve detection" on (with the version of the text agreed to) or off for the caller's device.
-- On gives a fresh random pseudonym; off deletes all of its samples and trips at once and drops the pseudonym.
create function public.set_training_consent(enabled boolean, version int)
returns boolean language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
  subj uuid;
begin
  if uid is null or not exists (select 1 from public.devices d where d.id = uid) then
    raise exception 'device not registered' using errcode = '42501';
  end if;
  if enabled is null or (enabled and (version is null or version not between 0 and 1000)) then
    raise exception 'enabled and a consent version 0..1000 are required' using errcode = '22023';
  end if;
  if enabled then
    update public.devices d
    set training_consent = true, training_consent_at = now(), training_consent_version = version,
        training_subject = coalesce(d.training_subject, gen_random_uuid())
    where d.id = uid;
  else
    select d.training_subject into subj from public.devices d where d.id = uid;
    delete from public.training_samples s where s.subject = subj;
    delete from public.training_trips t where t.subject = subj;
    update public.devices d set training_consent = false, training_consent_at = now(), training_subject = null
    where d.id = uid;
  end if;
  return enabled;
end;
$$;

-- Accepts {"app_version", "sdk", "brand", "samples": [<=100], "trips": [<=10]}, at most 1 MB (format: README).
-- Any bad element rejects the whole batch (22023). 42501 without consent; 54000 above 300 samples, 1 MB of
-- waveform or 20 trips per device per day, or 20,000 samples per day for the project; 53100 when the training
-- tables are over training_max_mb or the whole database is over 400 MB.
-- Duplicates are ignored. Returns {"samples": [client ids], "trips": [client ids]} the server holds.
create function public.submit_training_samples(batch jsonb)
returns jsonb language plpgsql security definer set search_path = '' as $$
declare
  uid uuid := auth.uid();
  subj uuid;
  smp jsonb;
  trp jsonb;
  max_mb bigint;
  n_new int := 0;
  b_new int := 0;
  t_new int := 0;
  q record;
begin
  select d.training_subject into subj from public.devices d where d.id = uid and d.training_consent;
  if uid is null or subj is null then
    raise exception 'no consent to help improve detection' using errcode = '42501';
  end if;
  if batch is null or jsonb_typeof(batch) <> 'object' or octet_length(batch::text) > 1000000 then
    raise exception 'batch must be a JSON object of at most 1 MB' using errcode = '22023';
  end if;
  smp := coalesce(batch -> 'samples', '[]'::jsonb);
  trp := coalesce(batch -> 'trips', '[]'::jsonb);
  if jsonb_typeof(smp) <> 'array' or jsonb_typeof(trp) <> 'array'
     or jsonb_array_length(smp) > 100 or jsonb_array_length(trp) > 10 then
    raise exception 'samples (<= 100) and trips (<= 10) must be arrays' using errcode = '22023';
  end if;
  if jsonb_array_length(smp) + jsonb_array_length(trp) = 0 then
    return jsonb_build_object('samples', '[]'::jsonb, 'trips', '[]'::jsonb);
  end if;
  -- Project-wide guard so the shared free database never fills (default 200 MB of the 500 MB).
  select coalesce((select case when a.value ~ '^[0-9]{1,6}$' then a.value::bigint end
                   from public.app_settings a where a.key = 'training_max_mb'), 200)
  into max_mb;
  if pg_total_relation_size('public.training_samples') + pg_total_relation_size('public.training_trips')
     + pg_total_relation_size('public.training_quota') >= max_mb * 1024 * 1024
     or pg_database_size(current_database()) >= 400 * 1024 * 1024 then
    raise exception 'training storage is full' using errcode = '53100';
  end if;
  begin
    with ins as (
      insert into public.training_samples
        (subject, client_sample_id, day, decision, reason, label_source, classification, placement,
         speed_kmh, heading_change_deg, gps_accuracy_m, peak, shape_score, first_down, roll_pitch_ratio, side_score,
         spot_id, sdk, app_version, brand, rate_hz, pre_ms, accel_v, gyro_roll, gyro_pitch)
      select subj, (e ->> 'client_sample_id')::uuid, (e ->> 'day')::date,
             e ->> 'decision', e ->> 'reason',
             case when e ->> 'decision' = 'user_mute' then 'user_mute' else 'engine' end,
             e ->> 'classification', e ->> 'placement',
             (e ->> 'speed_kmh')::real, (e ->> 'heading_change_deg')::real, (e ->> 'gps_accuracy_m')::real,
             (e ->> 'peak')::real, (e ->> 'shape_score')::real, (e ->> 'first_down')::boolean,
             (e ->> 'roll_pitch_ratio')::real, (e ->> 'side_score')::real,
             sp.id,
             (batch ->> 'sdk')::smallint, batch ->> 'app_version', lower(batch ->> 'brand'),
             (e ->> 'rate_hz')::smallint, (e ->> 'pre_ms')::smallint,
             decode(e ->> 'accel_v', 'base64'), decode(e ->> 'gyro_roll', 'base64'), decode(e ->> 'gyro_pitch', 'base64')
      from jsonb_array_elements(smp) e
      left join public.spots sp on sp.id = (e ->> 'spot_id')::bigint and sp.status = 'confirmed'
      where true  -- keeps the join's ON apart from ON CONFLICT
      on conflict (subject, client_sample_id) do nothing
      returning octet_length(accel_v) + coalesce(octet_length(gyro_roll) + octet_length(gyro_pitch), 0) as nb
    )
    select count(*)::int, coalesce(sum(nb), 0)::int into n_new, b_new from ins;
    with ins as (
      insert into public.training_trips
        (subject, client_trip_id, day, placement, sdk, app_version, brand, duration_s, distance_m,
         n_learned, n_hit, n_rejected, n_miss, n_pass_clear, n_user_mute, n_beeps, battery_start, battery_end,
         score, speeding_s, harsh_brakes, harsh_accels, harsh_corners, swerves, bumps_fast, phone_use)
      select subj, (e ->> 'client_trip_id')::uuid, (e ->> 'day')::date, e ->> 'placement',
             (batch ->> 'sdk')::smallint, batch ->> 'app_version', lower(batch ->> 'brand'),
             (e ->> 'duration_s')::int, (e ->> 'distance_m')::int,
             (e ->> 'n_learned')::int, (e ->> 'n_hit')::int, (e ->> 'n_rejected')::int, (e ->> 'n_miss')::int,
             (e ->> 'n_pass_clear')::int, (e ->> 'n_user_mute')::int, (e ->> 'n_beeps')::int,
             (e ->> 'battery_start')::smallint, (e ->> 'battery_end')::smallint, (e ->> 'score')::smallint,
             (e ->> 'speeding_s')::int, (e ->> 'harsh_brakes')::int, (e ->> 'harsh_accels')::int,
             (e ->> 'harsh_corners')::int, (e ->> 'swerves')::int, (e ->> 'bumps_fast')::int, (e ->> 'phone_use')::int
      from jsonb_array_elements(trp) e
      on conflict (subject, client_trip_id) do nothing
      returning 1
    )
    select count(*)::int into t_new from ins;
  exception when data_exception or check_violation or not_null_violation then
    raise exception 'invalid training batch: %', sqlerrm using errcode = '22023';
  end;
  -- The upsert locks the counter row, so parallel calls are counted one after the other.
  -- Going over a cap raises, which rolls back the whole call (inserts included).
  insert into public.training_quota as c (device_id, day, samples, bytes, trips)
  values (uid, current_date, n_new, b_new, t_new)
  on conflict (device_id, day) do update
    set samples = c.samples + excluded.samples, bytes = c.bytes + excluded.bytes, trips = c.trips + excluded.trips
  returning c.samples, c.bytes, c.trips into q;
  if q.samples > 300 or q.bytes > 1000000 or q.trips > 20 then
    raise exception 'daily training upload limit reached' using errcode = '54000';
  end if;
  insert into public.training_quota_total as t (day, samples) values (current_date, n_new)
  on conflict (day) do update set samples = t.samples + excluded.samples
  returning t.samples into n_new;
  if n_new > 20000 then
    raise exception 'daily project training limit reached' using errcode = '54000';
  end if;
  return jsonb_build_object(
    'samples', coalesce((select jsonb_agg(distinct e ->> 'client_sample_id') from jsonb_array_elements(smp) e), '[]'::jsonb),
    'trips', coalesce((select jsonb_agg(distinct e ->> 'client_trip_id') from jsonb_array_elements(trp) e), '[]'::jsonb));
end;
$$;

-- forget_me now names the training rows too (the pseudonym cascade would remove them anyway).
create or replace function public.forget_me()
returns void language plpgsql security definer set search_path = '' as $$
begin
  if auth.uid() is null then
    raise exception 'not signed in' using errcode = '42501';
  end if;
  delete from public.training_samples s
  where s.subject = (select d.training_subject from public.devices d where d.id = auth.uid());
  delete from public.training_trips t
  where t.subject = (select d.training_subject from public.devices d where d.id = auth.uid());
  delete from public.devices d where d.id = auth.uid();
end;
$$;

-- ---------------------------------------------------------------- server only: retention and export
-- Keeps 12 months of samples and trips (by server day) and 2 days of counters.
create function public.prune_training_data()
returns void language sql security definer set search_path = '' as $$
  delete from public.training_samples where received_on < (current_date - interval '12 months')::date;
  delete from public.training_trips where received_on < (current_date - interval '12 months')::date;
  delete from public.training_quota where day < current_date - 2;
  delete from public.training_quota_total where day < current_date - 2;
$$;

-- int16 little-endian bytes -> real[] in physical units (scale per unit).
create function public.training_i16(b bytea, scale real)
returns real[] language sql immutable set search_path = '' as $$
  select array_agg(((get_byte(b, 2 * i) | (get_byte(b, 2 * i + 1) << 8))
                    - case when get_byte(b, 2 * i + 1) >= 128 then 65536 else 0 end)::real * scale order by i)
  from generate_series(0, octet_length(b) / 2 - 1) i;
$$;

-- For offline learning (service role only): samples with waveforms decoded to m/s² and rad/s.
-- Trip summaries need no decoding: the service role reads public.training_trips directly.
create function public.training_export(since date default null)
returns setof jsonb language sql stable security definer set search_path = '' as $$
  select to_jsonb(s) - 'accel_v' - 'gyro_roll' - 'gyro_pitch' || jsonb_build_object(
           'accel_v', public.training_i16(s.accel_v, 0.004), 'gyro_roll', public.training_i16(s.gyro_roll, 0.001),
           'gyro_pitch', public.training_i16(s.gyro_pitch, 0.001))
  from public.training_samples s
  where (since is null or s.received_on >= since)
    and s.received_on >= (current_date - interval '12 months')::date  -- second safeguard if the prune job is missing
  order by s.id;
$$;

revoke execute on function public.set_training_consent(boolean, int) from public, anon;
revoke execute on function public.submit_training_samples(jsonb) from public, anon;
revoke execute on function public.prune_training_data() from public, anon, authenticated;
revoke execute on function public.training_i16(bytea, real) from public, anon, authenticated;
revoke execute on function public.training_export(date) from public, anon, authenticated;
grant execute on function public.set_training_consent(boolean, int) to authenticated;
grant execute on function public.submit_training_samples(jsonb) to authenticated;
grant execute on function public.training_export(date) to service_role;

-- Prune daily where pg_cron exists (same pattern as the other jobs).
do $$
begin
  if exists (select 1 from pg_available_extensions where name = 'pg_cron') then
    create extension if not exists pg_cron with schema pg_catalog;
    perform cron.schedule('prune-training-data', '41 3 * * *', 'select public.prune_training_data()');
  end if;
exception when others then
  raise notice 'pg_cron not scheduled: %', sqlerrm;
end;
$$;
